name: Release Major

on: workflow_dispatch

jobs:
  release-major:
    name: Release Major
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          scheme: semver
          increment: major
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: gh release create ${{steps.version.outputs.v-version}} --generate-notes
