on:
  - push
  - pull_request

name: Go
jobs:
  test:
    name: Test
    strategy:
      matrix:
        go-version: [ "1.21", "1.22", "1.23" ]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: "${{ runner.os }}-go${{ matrix.go-version }}-${{ hashFiles('**/go.mod') }}-${{ hashFiles('**/go.sum') }}"
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test -v -race ./...
  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: "${{ runner.os }}-release${{github.ref_name}}-${{ hashFiles('**/go.mod') }}-${{ hashFiles('**/go.sum') }}"
      - name: Release module
        run: GOPROXY=proxy.golang.org go list -m github.com/baptistecdr/controld-go@${{github.ref_name}}
